### ISSUE TITLE
Add NavigationButton

### ISSUE THREAD

**Issue by kenhowardpdx** [NathanWalker/nativescript-ng2-vscode-snippets#3]
Just thought I'd help you remember to add this snippet.

**Comment by NathanWalker** [comment]
closed via https://github.com/NathanWalker/nativescript-ng2-vscode-snippets/commit/1840233f2104d8b6476680c8f31f04e2dcf50b8d

Published with `1.2.0`, thanks for reminder @kenhowardpdx  👍
